-- MySQL Script generated by MySQL Workbench
-- mer. 24 avril 2019 17:24:49 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema psesi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema psesi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `psesi` ;
USE `psesi` ;

-- -----------------------------------------------------
-- Table `psesi`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psesi`.`user` ;

CREATE TABLE IF NOT EXISTS `psesi`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psesi`.`type_sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psesi`.`type_sensor` ;

CREATE TABLE IF NOT EXISTS `psesi`.`type_sensor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psesi`.`sensor_position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psesi`.`sensor_position` ;

CREATE TABLE IF NOT EXISTS `psesi`.`sensor_position` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psesi`.`sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psesi`.`sensor` ;

CREATE TABLE IF NOT EXISTS `psesi`.`sensor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type_sensor_id` INT UNSIGNED NOT NULL,
  `sensor_position_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `type_sensor_id`, `sensor_position_id`),
  INDEX `fk_sensor_type_sensor1_idx` (`type_sensor_id` ASC) VISIBLE,
  INDEX `fk_sensor_sensor_position1_idx` (`sensor_position_id` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_type_sensor1`
    FOREIGN KEY (`type_sensor_id`)
    REFERENCES `psesi`.`type_sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensor_sensor_position1`
    FOREIGN KEY (`sensor_position_id`)
    REFERENCES `psesi`.`sensor_position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psesi`.`type_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psesi`.`type_data` ;

CREATE TABLE IF NOT EXISTS `psesi`.`type_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psesi`.`data_int`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psesi`.`data_int` ;

CREATE TABLE IF NOT EXISTS `psesi`.`data_int` (
  `value` INT NOT NULL,
  PRIMARY KEY (`value`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psesi`.`data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psesi`.`data` ;

CREATE TABLE IF NOT EXISTS `psesi`.`data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT UNSIGNED NOT NULL,
  `type_data_id` INT UNSIGNED NOT NULL,
  `sensor_id` INT UNSIGNED NOT NULL,
  `sensor_type_sensor_id` INT UNSIGNED NOT NULL,
  `sensor_sensor_position_id` INT UNSIGNED NOT NULL,
  `data_int_value` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `type_data_id`, `data_int_value`),
  INDEX `fk_data_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_data_type_data1_idx` (`type_data_id` ASC) VISIBLE,
  INDEX `fk_data_sensor1_idx` (`sensor_id` ASC, `sensor_type_sensor_id` ASC, `sensor_sensor_position_id` ASC) VISIBLE,
  INDEX `fk_data_data_int1_idx` (`data_int_value` ASC) VISIBLE,
  CONSTRAINT `fk_data_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `psesi`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_type_data1`
    FOREIGN KEY (`type_data_id`)
    REFERENCES `psesi`.`type_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_sensor1`
    FOREIGN KEY (`sensor_id` , `sensor_type_sensor_id` , `sensor_sensor_position_id`)
    REFERENCES `psesi`.`sensor` (`id` , `type_sensor_id` , `sensor_position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_data_int1`
    FOREIGN KEY (`data_int_value`)
    REFERENCES `psesi`.`data_int` (`value`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
